local o = vim.o
local bo = vim.bo
local wo = vim.wo

--require('general')
require('devicons')
--require('statusline-config')
--require('deep_ocean')
--require('deep_ocean2')
-- require('evilline')
require('spaceline')
require('nvimtree-config')
require('colorizer-config')
require('autopairs-config')
require('bufferline-config')
--require('statusline')
require('lsp_config')
--require('snippets-config')
require('compe-config')
require('lsp/html-lsp')
require('lsp/php-lsp')
require('lsp/css-lsp')
require('lsp/json-lsp')
require('lsp/bash-lsp')
require('lsp/tsserver-lsp')
require('lsp/python-lsp')
