#!/bin/bash
pikman remove pika-gnome-desktop \
  pika-gnome-layouts \
  pika-gnome-settings \
  gdm3 \
  gnome-shell \
  gnome-session \
  gnome-session-xsession \
  gnome-themes-extra \
  appmenu-gtk2-module \
  appmenu-gtk3-module \
  at-spi2-core \
  baobab \
  brltty \
  chrome-gnome-shell \
  gir1.2-gmenu-3.0 \
  gkbd-capplet \
  glib-networking \
  gucharmap \
  gvfs-fuse \
  libglib2.0-bin \
  libpam-gnome-keyring \
  libproxy1-plugin-gsettings \
  libproxy1-plugin-webkit \
  librsvg2-common \
  system-config-printer-common \
  system-config-printer-udev \
  tracker \
  pika-welcome \
  xdg-desktop-portal-gnome \
  gnome-bluetooth \
  gnome-calculator \
  gnome-calendar \
  gnome-characters \
  gnome-clocks \
  gnome-console \
  gnome-contacts \
  gnome-control-center \
  gnome-firmware \
  gnome-keyring \
  gnome-logs \
  gnome-menus \
  gnome-online-accounts \
  gnome-photos \
  gnome-power-manager \
  gnome-remote-desktop \
  gnome-settings-daemon \
  gnome-shell-extension-manager \
  gnome-software \
  gnome-sushi \
  gnome-system-monitor \
  gnome-text-editor \
  gnome-tweaks \
  gnome-user-docs \
  gnome-user-share \
  gnome-video-effects \
  gnome-weather \
  nautilus \
  pavucontrol \
  seahorse \
  simple-scan \
  totem \
  zenity \
  yelp \
  gnome-shell-extension-supergfxctl-gex \
  gnome-software-plugin-deb \
  gnome-software-plugin-flatpak \
  gnome-software-plugin-fwupd \
  nautilus-share \
  network-manager-openvpn-gnome \
  network-manager-pptp-gnome \
  gnome-bluetooth-sendto -y
