# ~/.config/starship.toml

format = """
$username\
$hostname\
$directory\
$line_break\
$character"""

right_format = """
$git_branch\
$git_state\
$git_status\
$aws\
$azure\
$conda\
$cobol\
$conda\
$dart\
docker_context\
dotnet\
elixir\
$elm\
$gcloud\
$golang\
$hg_branch\
$java\
$julia\
$kotlin\
$lua\
$memory_usage\
$nim\
$nix_shell\
$nodejs\
$package\
$perl\
$php\
$python\
$ruby\
$rust\
$scala\
$shlvl\
$swift"""

[aws]
format = '[$symbol($profile )(\($region\) )]($style)'
symbol = "  "

[azure]
format = "[$symbol($subscription)]($style) "
symbol = "ﴃ "
style = "blue bold"

[character]
success_symbol = "[\u03BB](green bold)"
error_symbol = "[\u03BB](red)"
vicmd_symbol = "[\u03BB](purple)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[cobol]
format = "[$symbol$version]($style)"
symbol = " "
style = "blue bold"

[conda]
format = "[$symbol$environment]($style)"
symbol = " "
style = "green dimmed"

[dart]
format = "[$symbol$version]($style)"
symbol = " "
style = "blue bold"

[directory]
read_only = "  "
style = "green bold"

[docker_context]
format = "[$symbol$context]($style)"
symbol = " "
style = "blue bold"

[dotnet]
format = "[$symbol($version)(什 $tfm )]($style)"
symbol = " "
style = "blue bold"

[elixir]
#format = "[$symbol($version \(OTP $otp_version\))]($style)"
symbol = " "
style = "purple bold"

[elm]
format = "[$symbol($version)]($style)"
symbol = " "
style = "cyan bold"

[gcloud]
#format = "[$symbol$account(@$domain)(\($region\))]($style)"
symbol = " "
style = "blue bold"


[git_branch]
format = "[$symbol$branch]($style)"
style = "bright-black"
symbol = " "

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[golang]
format = "[$symbol$version]($style)"
symbol = " "
style = "cyan bold"

[hg_branch]
symbol = " "

[java]
format = "[$symbol$version]($style)"
symbol = " "
style = "red dimmed"

[julia]
format = "[$symbol$version]($style)"
symbol = " "
style = "purple bold"

[kotlin]
format = "[$symbol$version]($style)"
symbol = " "
style = "blue bold"

[lua]
format = "[$symbol$version]($style)"
symbol = " "
style = "blue bold"

[memory_usage]
symbol = "󰍛 "

[nim]
format = "[$symbol$version]($style)"
symbol = " "
style = "yellow bold"

[nix_shell]
#format = "[$symbol$state( \($name\))]($style)"
symbol = " "
style = "blue bold"

[nodejs]
format = "[$symbol($version )]($style)"
symbol = " "
style = "green bold"

[package]
symbol = "󰏗 "

[perl]
format = "[$symbol$version]($style)"
symbol = " "
style = "149 bold"

[php]
format = "[$symbol$version]($style)"
symbol = " "
style = "147 bold"

[python]
format = "[$symbol$version]($style)"
symbol = " "
style = "yellow bold"

[ruby]
format = "[$symbol$version]($style)"
symbol = " "
style = "red bold"

[rust]
format = "[$symbol$version]($style)"
symbol = " "
style = "red bold"

[scala]
format = "[$symbol$version]($style)"
symbol = " "
style = "red dimmed"

[shell]
fish_indicator = ""
powershell_indicator = "_"
bash_indicator = ""
zsh_indicator = ""
unknown_indicator = "mystery shell"
style = "cyan bold"
disabled = false

[shlvl]
symbol = " "

[swift]
format = "[$symbol$version]($style)"
symbol = "ﯣ "
style = "blue dimmed bold"
