[UNKNOWN_153200AB_0000]
dpi_x = 3200
dpi_y = 3200
poll_rate = 500
backlight_active = True
backlight_brightness = 0
backlight_effect = none
backlight_colors = 0 255 0 0 255 255 0 0 255
backlight_speed = 1
backlight_wave_dir = 1
logo_active = True
logo_brightness = 75
logo_effect = spectrum
logo_colors = 0 255 0 0 255 255 0 0 255
logo_speed = 1
logo_wave_dir = 1
scroll_active = True
scroll_brightness = 75
scroll_effect = spectrum
scroll_colors = 0 255 0 0 255 255 0 0 255
scroll_speed = 1
scroll_wave_dir = 1

[UNKNOWN_153200AB_0001]
dpi_x = 3200
dpi_y = 3200
poll_rate = 1000
backlight_active = True
backlight_brightness = 75
backlight_effect = none
backlight_colors = 0 255 0 0 255 255 0 0 255
backlight_speed = 1
backlight_wave_dir = 1
logo_active = True
logo_brightness = 75
logo_effect = none
logo_colors = 0 255 0 0 255 255 0 0 255
logo_speed = 1
logo_wave_dir = 1
scroll_active = True
scroll_brightness = 75
scroll_effect = none
scroll_colors = 0 255 0 0 255 255 0 0 255
scroll_speed = 1
scroll_wave_dir = 1

[632511H26200388]
dpi_x = 3200
dpi_y = 3200
poll_rate = 1000
backlight_active = True
backlight_brightness = 95
backlight_effect = none
backlight_colors = 0 255 0 0 255 255 0 0 255
backlight_speed = 1
backlight_wave_dir = 1
logo_active = True
logo_brightness = 75
logo_effect = none
logo_colors = 0 255 0 0 255 255 0 0 255
logo_speed = 1
logo_wave_dir = 1
scroll_active = True
scroll_brightness = 75
scroll_effect = none
scroll_colors = 0 255 0 0 255 255 0 0 255
scroll_speed = 1
scroll_wave_dir = 1

