# Set mangohud enabled all the time (maybe better to put this into a user_settings.py file)
MANGOHUD=1

# Proton Related
PROTON_ENABLE_WAYLAND=1

# FSR 4
PROTON_FSR4_UPGRADE=1
PROTON_FSR4_INDICATOR=0

DXVK_FILTER_DEVICE_NAME="AMD Radeon RX 9070"
VKD3D_FRAME_RATE=162
VKD3D_FEATURE_LEVEL=12_2
