# prioritized fallback list for applications using SDL
#   doing it this way will attempt to load the app in wayland first and if it fails then falls back to x11
SDL_VIDEODRIVER=wayland,x11
# Load electron apps with the ozone platform flag set to auto (needed for legacy electron apps)
ELECTRON_OZONE_PLATFORM_HINT=auto
