if vim.g.vscode then
  vim.cmd('source ~/.config/nvim/lua/vscode/init.vim')
else   
vim.cmd('source $HOME/.config/nvim/mappings.vim')

require('settings')
require('plugins')
require('devicons')
--require('statusline-config')
--require('deep_ocean')
--require('deep_ocean2')
-- require('evilline')
require('spaceline')
require('nvimtree')
vim.cmd('source $HOME/.config/nvim/lua/nvimtree/nvimtree-config.vim')
require('colorizer-config')
require('autopairs-config')
require('bufferline-config')
require('treesitter-config')
--require('statusline')
require('lsp_config')
--require('snippets-config')
require('compe-config')
require('lsp/html-lsp')
require('lsp/php-lsp')
require('lsp/css-lsp') 
require('lsp/json-lsp')
require('lsp/bash-lsp')
require('lsp/tsserver-lsp')
require('lsp/python-lsp')
--vim.cmd('source $HOME/.config/nvim/colorschemes.vim')
vim.cmd('source $HOME/.config/nvim/plugins.d/ale.vim')
vim.cmd('source $HOME/.config/nvim/plugins.d/prettier.vim')
require('colorscheme')
end
